---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "snowplow-scala-stream-collector-kafka.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "snowplow-scala-stream-collector-kafka.name" . }}
    helm.sh/chart: {{ include "snowplow-scala-stream-collector-kafka.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.hocon: |
    {{- .Values.config | nindent 4 }}
