---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snowplow-scala-stream-collector-kafka.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "snowplow-scala-stream-collector-kafka.name" . }}
    helm.sh/chart: {{ include "snowplow-scala-stream-collector-kafka.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "snowplow-scala-stream-collector-kafka.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "snowplow-scala-stream-collector-kafka.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      hostname: {{ include "snowplow-scala-stream-collector-kafka.fullname" . }}
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: jmx
              containerPort: 1099
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 8
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 8
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
